"""initial_master_and_jurnal_tables

Revision ID: 1f869e1d16af
Revises: 
Create Date: 2026-08-11 23:23:58.862185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f869e1d16af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('akun_perkiraan',
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('header', sa.Enum('AKTIVA', 'KEWAJIBAN', 'MODAL', 'PENDAPATAN', 'HPP', 'BEBAN', name='headercoa'), nullable=False),
    sa.Column('tingkat', sa.Enum('HEADER', 'GROUP', 'DETAIL', name='tingkatakun'), nullable=False),
    sa.Column('induk_id', sa.UUID(), nullable=True),
    sa.Column('induk_kode', sa.String(length=20), nullable=True),
    sa.Column('saldo_normal', sa.Enum('DEBIT', 'KREDIT', name='saldonormal'), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['induk_id'], ['akun_perkiraan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_akun_perkiraan_kode'), 'akun_perkiraan', ['kode'], unique=True)
    op.create_table('biaya_tambahan',
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('jenis', sa.String(length=50), nullable=False),
    sa.Column('nilai', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gudang',
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('total_barang', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kategori_aset',
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kategori_barang',
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pengguna',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRATOR', 'MANAJER_KEUANGAN', 'STAFF_AKUNTANSI', 'STAFF_GUDANG', 'STAFF_PENJUALAN', name='rolepengguna'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('terakhir_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pengguna_email'), 'pengguna', ['email'], unique=True)
    op.create_index(op.f('ix_pengguna_username'), 'pengguna', ['username'], unique=True)
    op.create_table('satuan',
    sa.Column('nama', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syarat_bayar',
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('hari', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barang',
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('kategori_id', sa.UUID(), nullable=False),
    sa.Column('satuan_id', sa.UUID(), nullable=False),
    sa.Column('harga_pokok', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('stok_minimum', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori_barang.id'], ),
    sa.ForeignKeyConstraint(['satuan_id'], ['satuan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barang_kode'), 'barang', ['kode'], unique=True)
    op.create_table('jurnal_umum',
    sa.Column('no_jurnal', sa.String(length=30), nullable=False),
    sa.Column('tanggal', sa.String(length=10), nullable=False),
    sa.Column('tipe_transaksi', sa.String(length=100), nullable=True),
    sa.Column('ref_module', sa.Enum('PEMBAYARAN', 'PENERIMAAN', 'TRANSFER_BANK', 'SALES_ORDER', 'SALES_INVOICE', 'SALES_RETUR', 'PURCHASE_ORDER', 'PURCHASE_INVOICE', 'PURCHASE_RETUR', 'PENYESUAIAN_STOK', 'PENYUSUTAN', 'MANUAL', name='refmodule'), nullable=True),
    sa.Column('ref_no', sa.String(length=30), nullable=True),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('total_debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_kredit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('POSTED', 'DRAFT', name='statusjurnal'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['pengguna.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jurnal_umum_no_jurnal'), 'jurnal_umum', ['no_jurnal'], unique=True)
    op.create_index(op.f('ix_jurnal_umum_ref_no'), 'jurnal_umum', ['ref_no'], unique=False)
    op.create_table('karyawan',
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('jabatan', sa.String(length=100), nullable=True),
    sa.Column('departemen', sa.Enum('DIREKSI', 'KEUANGAN', 'AKUNTANSI', 'GUDANG', 'PENJUALAN', 'ADMINISTRASI', 'PRODUKSI', name='departemen'), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('no_hp', sa.String(length=20), nullable=True),
    sa.Column('akun_piutang_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['akun_piutang_id'], ['akun_perkiraan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_karyawan_nik'), 'karyawan', ['nik'], unique=True)
    op.create_table('kas_bank_akun',
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('jenis', sa.Enum('KAS', 'BANK', name='jeniskasbank'), nullable=False),
    sa.Column('akun_perkiraan_id', sa.UUID(), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['akun_perkiraan_id'], ['akun_perkiraan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kas_bank_akun_kode'), 'kas_bank_akun', ['kode'], unique=True)
    op.create_table('pelanggan',
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('telepon', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('kontak_person', sa.String(length=150), nullable=True),
    sa.Column('akun_piutang_id', sa.UUID(), nullable=False),
    sa.Column('syarat_bayar_default', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['akun_piutang_id'], ['akun_perkiraan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pelanggan_kode'), 'pelanggan', ['kode'], unique=True)
    op.create_table('supplier',
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('telepon', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('kontak_person', sa.String(length=150), nullable=True),
    sa.Column('akun_hutang_id', sa.UUID(), nullable=False),
    sa.Column('syarat_bayar_default', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['akun_hutang_id'], ['akun_perkiraan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_kode'), 'supplier', ['kode'], unique=True)
    op.create_table('jurnal_detail',
    sa.Column('jurnal_umum_id', sa.UUID(), nullable=False),
    sa.Column('akun_perkiraan_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('kredit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['akun_perkiraan_id'], ['akun_perkiraan.id'], ),
    sa.ForeignKeyConstraint(['jurnal_umum_id'], ['jurnal_umum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jurnal_detail')
    op.drop_index(op.f('ix_supplier_kode'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_pelanggan_kode'), table_name='pelanggan')
    op.drop_table('pelanggan')
    op.drop_index(op.f('ix_kas_bank_akun_kode'), table_name='kas_bank_akun')
    op.drop_table('kas_bank_akun')
    op.drop_index(op.f('ix_karyawan_nik'), table_name='karyawan')
    op.drop_table('karyawan')
    op.drop_index(op.f('ix_jurnal_umum_ref_no'), table_name='jurnal_umum')
    op.drop_index(op.f('ix_jurnal_umum_no_jurnal'), table_name='jurnal_umum')
    op.drop_table('jurnal_umum')
    op.drop_index(op.f('ix_barang_kode'), table_name='barang')
    op.drop_table('barang')
    op.drop_table('syarat_bayar')
    op.drop_table('satuan')
    op.drop_index(op.f('ix_pengguna_username'), table_name='pengguna')
    op.drop_index(op.f('ix_pengguna_email'), table_name='pengguna')
    op.drop_table('pengguna')
    op.drop_table('kategori_barang')
    op.drop_table('kategori_aset')
    op.drop_table('gudang')
    op.drop_table('biaya_tambahan')
    op.drop_index(op.f('ix_akun_perkiraan_kode'), table_name='akun_perkiraan')
    op.drop_table('akun_perkiraan')
    # ### end Alembic commands ###
